channels:
  - conda-forge
dependencies:
  - pandoc
  - sphinx
  - nbsphinx
  - jupyterlab-git
#  - jupyter-offlinenotebook  
#  - jupyter_contrib_nbextensions
 - pip
 - pip: 
   - nbdime
#   - bash_kernel
