channels:
    - conda-forge
    - conda-forge/label/prerelease-jupyterlab
dependencies:
    - voila
    - nbgitpuller
    - pip
    - pip: 
        - dash
        - requests
        - flask
        - retrying
        - ipython
        - ipykernel
        - ansi2html
        - jupyter-server-proxy
        - jupyter-dash
