channels:
  - conda-forge
  - pkgw/label/superseded
dependencies:
#   - jupyter-offlinenotebook  
  - jupyter_contrib_nbextensions
  - texlive-core
  - texlive-selected
  - pip
  - pip: 
    - bash_kernel
